package com.TestDEVPro.domain.core;

import javax.persistence.Id;

import javax.persistence.Column;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;

import javax.persistence.OneToMany;

import javax.persistence.Table;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name="Ibmdata")
 @JsonIgnoreProperties(ignoreUnknown = true)
 @JsonInclude(Include.NON_NULL)
 

@ApiModel( value = "Ibmdata", description = "ibmdata" )
public class Ibmdata  implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	private	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	private	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	private	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	private	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	private	long Updated_by;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lotusseller_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Quarter;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Products;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oldforecasttype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lastupdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Noteid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Projdur;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String History;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Rolesuser;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Estsigndate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Technology;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lotusseller;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pricecaselink;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Modified;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Doclink;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Href;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sowcurrency;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Client;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Spif;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Territory;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Created;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Roles;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Engagementmanager;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Project;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Keytrans;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecast;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sowamount;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Region;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Revenuetype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Authors;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Weekp;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Unid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Mthadjfst;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Linkyesno;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpoffering;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bdm;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Prjstartdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dbserver;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpleadsource;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecastsw;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecastview;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Mdoc;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Quote;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ssr;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Form;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sendforecastsw;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecasttype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Salesincentive;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setLotusseller_1(String Lotusseller_1) {
		this.Lotusseller_1 = Lotusseller_1;
	}


	public String getLotusseller_1() {
		return Lotusseller_1;
	}

	public void setQuarter(String Quarter) {
		this.Quarter = Quarter;
	}


	public String getQuarter() {
		return Quarter;
	}

	public void setProducts(String Products) {
		this.Products = Products;
	}


	public String getProducts() {
		return Products;
	}

	public void setOldforecasttype(String Oldforecasttype) {
		this.Oldforecasttype = Oldforecasttype;
	}


	public String getOldforecasttype() {
		return Oldforecasttype;
	}

	public void setLastupdate(String Lastupdate) {
		this.Lastupdate = Lastupdate;
	}


	public String getLastupdate() {
		return Lastupdate;
	}

	public void setNoteid(String Noteid) {
		this.Noteid = Noteid;
	}


	public String getNoteid() {
		return Noteid;
	}

	public void setProjdur(String Projdur) {
		this.Projdur = Projdur;
	}


	public String getProjdur() {
		return Projdur;
	}

	public void setHistory(String History) {
		this.History = History;
	}


	public String getHistory() {
		return History;
	}

	public void setRolesuser(String Rolesuser) {
		this.Rolesuser = Rolesuser;
	}


	public String getRolesuser() {
		return Rolesuser;
	}

	public void setEstsigndate(String Estsigndate) {
		this.Estsigndate = Estsigndate;
	}


	public String getEstsigndate() {
		return Estsigndate;
	}

	public void setTechnology(String Technology) {
		this.Technology = Technology;
	}


	public String getTechnology() {
		return Technology;
	}

	public void setLotusseller(String Lotusseller) {
		this.Lotusseller = Lotusseller;
	}


	public String getLotusseller() {
		return Lotusseller;
	}

	public void setPricecaselink(String Pricecaselink) {
		this.Pricecaselink = Pricecaselink;
	}


	public String getPricecaselink() {
		return Pricecaselink;
	}

	public void setModified(String Modified) {
		this.Modified = Modified;
	}


	public String getModified() {
		return Modified;
	}

	public void setDoclink(String Doclink) {
		this.Doclink = Doclink;
	}


	public String getDoclink() {
		return Doclink;
	}

	public void setHref(String Href) {
		this.Href = Href;
	}


	public String getHref() {
		return Href;
	}

	public void setSowcurrency(String Sowcurrency) {
		this.Sowcurrency = Sowcurrency;
	}


	public String getSowcurrency() {
		return Sowcurrency;
	}

	public void setClient(String Client) {
		this.Client = Client;
	}


	public String getClient() {
		return Client;
	}

	public void setSpif(String Spif) {
		this.Spif = Spif;
	}


	public String getSpif() {
		return Spif;
	}

	public void setTerritory(String Territory) {
		this.Territory = Territory;
	}


	public String getTerritory() {
		return Territory;
	}

	public void setCreated(String Created) {
		this.Created = Created;
	}


	public String getCreated() {
		return Created;
	}

	public void setRoles(String Roles) {
		this.Roles = Roles;
	}


	public String getRoles() {
		return Roles;
	}

	public void setEngagementmanager(String Engagementmanager) {
		this.Engagementmanager = Engagementmanager;
	}


	public String getEngagementmanager() {
		return Engagementmanager;
	}

	public void setProject(String Project) {
		this.Project = Project;
	}


	public String getProject() {
		return Project;
	}

	public void setKeytrans(String Keytrans) {
		this.Keytrans = Keytrans;
	}


	public String getKeytrans() {
		return Keytrans;
	}

	public void setForecast(String Forecast) {
		this.Forecast = Forecast;
	}


	public String getForecast() {
		return Forecast;
	}

	public void setSowamount(String Sowamount) {
		this.Sowamount = Sowamount;
	}


	public String getSowamount() {
		return Sowamount;
	}

	public void setRegion(String Region) {
		this.Region = Region;
	}


	public String getRegion() {
		return Region;
	}

	public void setRevenuetype(String Revenuetype) {
		this.Revenuetype = Revenuetype;
	}


	public String getRevenuetype() {
		return Revenuetype;
	}

	public void setAuthors(String Authors) {
		this.Authors = Authors;
	}


	public String getAuthors() {
		return Authors;
	}

	public void setWeekp(String Weekp) {
		this.Weekp = Weekp;
	}


	public String getWeekp() {
		return Weekp;
	}

	public void setUnid(String Unid) {
		this.Unid = Unid;
	}


	public String getUnid() {
		return Unid;
	}

	public void setMthadjfst(String Mthadjfst) {
		this.Mthadjfst = Mthadjfst;
	}


	public String getMthadjfst() {
		return Mthadjfst;
	}

	public void setLinkyesno(String Linkyesno) {
		this.Linkyesno = Linkyesno;
	}


	public String getLinkyesno() {
		return Linkyesno;
	}

	public void setAvpoffering(String Avpoffering) {
		this.Avpoffering = Avpoffering;
	}


	public String getAvpoffering() {
		return Avpoffering;
	}

	public void setBdm(String Bdm) {
		this.Bdm = Bdm;
	}


	public String getBdm() {
		return Bdm;
	}

	public void setPrjstartdate(String Prjstartdate) {
		this.Prjstartdate = Prjstartdate;
	}


	public String getPrjstartdate() {
		return Prjstartdate;
	}

	public void setDbserver(String Dbserver) {
		this.Dbserver = Dbserver;
	}


	public String getDbserver() {
		return Dbserver;
	}

	public void setAvpleadsource(String Avpleadsource) {
		this.Avpleadsource = Avpleadsource;
	}


	public String getAvpleadsource() {
		return Avpleadsource;
	}

	public void setForecastsw(String Forecastsw) {
		this.Forecastsw = Forecastsw;
	}


	public String getForecastsw() {
		return Forecastsw;
	}

	public void setForecastview(String Forecastview) {
		this.Forecastview = Forecastview;
	}


	public String getForecastview() {
		return Forecastview;
	}

	public void setMdoc(String Mdoc) {
		this.Mdoc = Mdoc;
	}


	public String getMdoc() {
		return Mdoc;
	}

	public void setQuote(String Quote) {
		this.Quote = Quote;
	}


	public String getQuote() {
		return Quote;
	}

	public void setSsr(String Ssr) {
		this.Ssr = Ssr;
	}


	public String getSsr() {
		return Ssr;
	}

	public void setForm(String Form) {
		this.Form = Form;
	}


	public String getForm() {
		return Form;
	}

	public void setSendforecastsw(String Sendforecastsw) {
		this.Sendforecastsw = Sendforecastsw;
	}


	public String getSendforecastsw() {
		return Sendforecastsw;
	}

	public void setForecasttype(String Forecasttype) {
		this.Forecasttype = Forecasttype;
	}


	public String getForecasttype() {
		return Forecasttype;
	}

	public void setSalesincentive(String Salesincentive) {
		this.Salesincentive = Salesincentive;
	}


	public String getSalesincentive() {
		return Salesincentive;
	}




}