/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/


USE testdevpro;

CREATE TABLE Ibmdata(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
lotusseller_1 varchar(255),
quarter varchar(255),
products varchar(255),
oldforecasttype varchar(255),
lastupdate varchar(255),
noteid varchar(255),
projdur varchar(255),
history varchar(255),
rolesuser varchar(255),
estsigndate varchar(255),
technology varchar(255),
lotusseller varchar(255),
pricecaselink varchar(255),
modified varchar(255),
doclink varchar(255),
href varchar(255),
sowcurrency varchar(255),
client varchar(255),
spif varchar(255),
territory varchar(255),
created varchar(255),
roles varchar(255),
engagementmanager varchar(255),
project varchar(255),
keytrans varchar(255),
forecast varchar(255),
sowamount varchar(255),
region varchar(255),
revenuetype varchar(255),
authors varchar(255),
weekp varchar(255),
unid varchar(255),
mthadjfst varchar(255),
linkyesno varchar(255),
avpoffering varchar(255),
bdm varchar(255),
prjstartdate varchar(255),
dbserver varchar(255),
avpleadsource varchar(255),
forecastsw varchar(255),
forecastview varchar(255),
mdoc varchar(255),
quote varchar(255),
ssr varchar(255),
form varchar(255),
sendforecastsw varchar(255),
forecasttype varchar(255),
salesincentive varchar(255),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

